version: "3"
services:
  rosalie:
    image: $HUB_URL:$PROD_TAG
    restart: always
    networks:
      - web
      - db
    ports:
      - "8080:80"
    environment:
      - VIRTUAL_HOST=rosalie.036.fr
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=rosalie.036.fr
      - LETSENCRYPT_EMAIL=sushifu@gmx.fr
      - DB_NAME=rosalie
      - DB_USER=rosalie
      - DB_URL=postgres-dev
      - PORT=8080
networks:
  db:
    external: true
  web:
    external: true
